### ISSUE TITLE
database.pkl doesn't get created

### ISSUE THREAD

**Issue by jerpint** [Epistimio/hydra_orion_sweeper#2]
when running the example script, the file `outputs/$DATE/$TIME/optimization_results.yaml` is materialized, however, there is no sign of the `database.pkl` file anywhere even though it is specified in the config.

Running

```
cd ~/hydra_orion_sweeper/example 
python my_app.py -m
```

Then

    tree multirun

Gives

```
multirun
└── 2022-07-22
    └── 23-40-44
        ├── 0
        │   └── my_app.log
...
        ├── 98
        │   └── my_app.log
        ├── 99
        │   └── my_app.log
        └── optimization_results.yaml
```

But no sign of a `database.pkl` file

**Comment by bouthilx** [comment]
Hi @jerpint! Can you please share how you specify your database file in your config?

**Comment by jerpint** [comment]
Hi @bouthilx I just used the same config as in the `example` folder, this one: https://github.com/Epistimio/hydra_orion_sweeper/blob/master/example/config.yaml

**Comment by Delaunay** [comment]
@jerpint  should be fixed now
